version: "3"

services:
  mysql_cpp:
    image: mariadb:10.2
    container_name: toko_fandi
    restart: unless-stopped
    tty: true
    ports:
      - "33215:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: p455w0rd
      MYSQL_ROOT_PASSWORD: p455w0rd
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    read_only: false
