@startuml menu_makan

left to right direction

actor user

rectangle menuMakan {
    user -- (Pilih Menu)

    (Pilih Menu) --> (choice 1) : pilih
    (Pilih Menu) --> (choice 2) : pilih
    (Pilih Menu) --> (choice 3) : pilih
    
    (choice 1) --> (Menu Makanan) : include
    (choice 2) --> (Menu Minuman) : include
    (choice 3) --> (exit)
    
    (Menu Makanan) --> (Pecel Lele) : pilih
    (Menu Makanan) --> (Nasi Goreng) : pilih
    (Menu Makanan) --> (Kembali) : pilih
    (Kembali) --> (Pilih Menu) : return
    
    (Menu Minuman) --> (teh manis) : pilih
    (Menu Minuman) --> (teh pucuk) : pilih
    (Menu Minuman) --> (Kembali) : pilih
    (Kembali) --> (Pilih Menu) : return
    
    (Pecel Lele) --> (qty) : input
    (Nasi Goreng) --> (qty) : input
    (teh manis) --> (qty) : input
    (teh pucuk) --> (qty) : input
    
    (qty) --> (Pilih Menu) : return
    (exit) --> (total)
    (total) --> (selesai)
}

@enduml
