version: "3"

services:
  db:
    image: mariadb:10.2
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "31234:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    read_only: false
